config/routes.rb
Rails.application.routes.draw do
 get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root :to => 'questions#index'
  resources :sessions
  resources :users
  resources :questions do
    resources :answers
  end
  resources :votes
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates_presence_of :content, :question_id, :user_id

  belongs_to :user
  belongs_to :question
  has_many :votes
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates_presence_of :user_id, :content

  belongs_to :user
  has_many :tags
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_uniqueness_of :email
  validates_presence_of :email

  has_many :questions
  has_many :answers
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user

  validates_presence_of :user_id, :answer_id
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    if @answer.save
      respond_to do |format|
        format.html { redirect_to question_url(@question), notice: "Please enter a valid question"}
        format.js
      end
    end
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = @question.answer.new(answer_params)
    @vote = Vote.new
  end

  private
  def answer_params
    params.require(:answer).permit(:id, :content, :question_id).merge(user_id: current_user.id, question_id: @question.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      respond_to do |format|
        format.html { redirect_to questions_url }
        format.js
      end
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @vote = Vote.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(params[:question])
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.js
    end
  end

  private
  def question_params
    params.require(:question).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class CotesController < ApplicationController

  def new
    @vote = Votes.new
  end

  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      respond_to do |format|
        format.html { redirect_to question_url(@question)}
        format.js
      end
    end
  end

  private
  def vote_params
    params.require(:vote).permit(:answer_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_answer.html.erb
<div class="row">
  <div class="col-md-3">
    <%= form_for Vote.new, remote: true do |f| %>
    <%= f.hidden_field :answer_id, :value => answer.id %>
    <%= f.submit %>
    <% end %>

    <span class="vote"><%= answer.votes.count %></span></p>
  </div>
  <div class="col-md-9">
    <%= answer.content %>
    <br>
    <%= answer.user.email %>
  </div>
</div>
<br>
<br>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer], html: { id: "question", class: "form"}, remote: true do |f| %>
  <%= render 'layouts/errors', :object => @answer %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <%= f.submit "Add Answer", id: "question", class: "btn btn-primary" %>
<% end %>

app/views/answers/create.js.erb
$('#question').remove();
$('#new-link').show();
$('#answers_list').append('<%= j render(@answer) %>');

app/views/answers/new.html.erb
<%= render 'form' %>

app/views/answers/new.js.erb
$('#new-link').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <div class="container">
    <header class="header">
    <nav>
        <ul class="nav nav-pills pull-right">
          <% if current_user %>
            <li><%= link_to user_path(current_user) do %><span class="glyphicon glyphicon-user"></span><%= current_user.email %><% end %></li>
            <li><%= link_to "Log Out", logout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Log In", login_path %></li>
          <% end %>
        </ul>
      </nav>
<%= flash[:notice] %>
<%= flash[:alert] %>
<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, html: {class: "form"}, remote: true do |f| %>
  <%= render 'layouts/errors', :object => @question %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>

  <%= f.submit "Ask Question", class: "btn btn-primary" %>
  <% end %>

app/views/questions/_question.html.erb
<p>
  <%= link_to "#{question.content}", question_path(question) %>
  posted by
  <%= question.user.email %>
</p>

app/views/questions/create.js.erb
$('#question').remove();
$('#new_link').show();
$('#questions_list').append('<% j render(@question) %>');

app/views/questions/index.html.erb
<h1>Questions</h1>

<div id="questions_list">
<%= render @questions %>
</div>

<%= link_to "New Question", new_question_path, id: "new_link", class: "btn btn-default", remote: true %>

app/views/questions/new.js.erb
$('#new-link').hide().after('<%= j render("form") %>');

app/views/questions/show.html.erb
<h2><%= @question.content %></h2>
<br>
<%= link_to "Answer Question", new_question_answer_path(@question), class: "btn btn-default", id: "new-link", remote: true %>

<br>
<h3>Answers:</h3>
<br>
<div id="answers_list">
  <%= render @answers %>
</div>

app/views/questions/update.js.erb
<% if @question.upvote? %>
  $('#edit_question_<%= @question.id %>').appendTo('#complete_quiestions');
  <% else %>
    $('#edit_question_<%= @question.id %>').appendTo('#incomplete_questions');
    <% end %>

app/views/users/_form.html.erb
<%= form_for @user, html: {class: "form"} do |f| %>
  <%= render 'layouts/errors', :object => @user %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/new.html.erb
<div class="new">
  <h1>Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/votes/_form.html.erb
<%= form_for vote, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update" %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/votes/create.js.erb
jQuery.fn.refreshOnClick = function() {
  this.find('input[type=submit]').click(function() {
    $(this).hide();
  });
  return this;
}

$(function() {
  $('.vote').refreshOnClick();
});